# Generated by Django 5.0.12 on 2025-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleados', models.AutoField(db_column='Id_Empleados', primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(blank=True, db_column='Cedula', null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=150, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='Fecha_Ingreso', null=True)),
                ('id_roles', models.IntegerField(blank=True, db_column='Id_Roles', null=True)),
            ],
            options={
                'db_table': 'vw_Empleados_Con_Permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permisos', models.AutoField(db_column='Id_Permisos', primary_key=True, serialize=False)),
                ('id_roles', models.IntegerField(db_column='Id_Roles')),
                ('tabla', models.CharField(db_column='Tabla', max_length=200)),
                ('tipo_permiso', models.CharField(db_column='Tipo_Permiso', max_length=200)),
            ],
            options={
                'db_table': 'TbPermisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id_registros', models.AutoField(db_column='Id_Registros', primary_key=True, serialize=False)),
                ('id_roles', models.IntegerField(blank=True, db_column='Id_Roles', null=True)),
                ('fecha_acceso', models.DateField(blank=True, db_column='Fecha_Acceso', null=True)),
                ('id_usuarios', models.IntegerField(blank=True, db_column='Id_Usuarios', null=True)),
                ('tabla', models.CharField(blank=True, db_column='Tabla', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TbRegistros',
                'managed': False,
            },
        ),
    ]
